### ISSUE TITLE
1.4.0 changed casing of generated keys class

### ISSUE THREAD

**Issue by esttorhe** [orta/cocoapods-keys#100]
Between `1.3.2` and `1.4.0` there was a change in the casing of the generated class; thus, running `pod install` after upgrading to the latest version was causing my app to stop compiling (because of the different names).

You can check my commit referencing this issue here: esttorhe/SlackTeamExplorer@b9781e5a94fd96abcbacba6db6be80

That project is also a sample code for the issue.

**Comment by nubbel** [comment]
:+1:

**Comment by orta** [comment]
Indeed it did: https://github.com/orta/cocoapods-keys/compare/v1.3.2...v1.4.0#diff-21575c23a6cb1c792dfdece197325d79R13

I think I prefer the old behavior ( all of our apps are one word, so we didn't notice a change. )

**Comment by esttorhe** [comment]
I do like the old behavior better but; maybe there was a reason behind this change.

Do you know if it was due to something else «requiring» this change @orta or was it purely «maintenance» coding that added this change?
