### ISSUE TITLE
Adding keys to project dir

### ISSUE THREAD

**Issue by x2on** [orta/cocoapods-keys#105]
Hi,

is there a way to add the secret keys to the project dir instead of Keychain or ENV?
I would add it to the git repository (just a private git repo), because asking for all the keys on different machines are to complicated.

Any ideas how to solve that?

**Comment by orta** [comment]
ENV works fine :+1: - this is how we do CI in Artsy - I'll update the README to say this

**Comment by orta** [comment]
https://github.com/orta/cocoapods-keys/commit/3f59570835eb47430d0b8049d280f7cd33c4640d

**Comment by x2on** [comment]
Thanks for the update. How do you handle that everyone in the team have the same keys, and if you need to change one?

**Comment by x2on** [comment]
I just added a PR to make this easier. :)

**Comment by orta** [comment]
Only the CI uses the env vars, everyone else uses Keychain + 1Password on our side (we might be a smaller team, so it's no worry for us yet )
