### ISSUE TITLE
Project build errors on run script phase using `pod keys get`

### ISSUE THREAD

**Issue by ruddfawcett** [orta/cocoapods-keys#116]
**Background**
You used to be able to use `pod keys get KEY_NAME` in a run script phase, like with projects using Crashlytics (#18), like so:

```bash
"${PODS_ROOT}/Fabric/Fabric.framework/run" pod keys get KEY_NAME
```
**Issue**
I have revisited Crashlytics (now Fabric), and was trying to use the same approach.  However, upon many a failed build and further investigation, I found that calling `pod keys get` caused a crash:

```
[33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding. Consider adding the following to ~/.profile: export LANG=en_US.UTF-8 
[0m [!] Unknown command: `get` Usage: $ pod keys [COMMAND] CocoaPods Keys will store sensitive data in your Mac's keychain. Then on running pod install they will be installed into your app's source code via the Pods library. Commands: > list Lists all known keys and values. + set A set values for keys. Options: --silent Show nothing --verbose Show more debugging information --no-ansi Show output without ANSI codes --help Show help banner of specified command
```
<img width="548" alt="screen shot 2015-10-28 at 1 25 35 am" src="https://cloud.githubusercontent.com/assets/3122471/10780364/0747993c-7d13-11e5-8bf4-0584cc8c28fc.png">

**Reproducing**
1. Create/use an Xcode project that utilizes `cocoapods-keys`
2. Add the following run script:
```bash
echo `pod keys get KEY_NAME`
```

**Note:** This may just be affecting my computer?  Haven't gotten a chance to test on another one.  However, I used this same approach earlier in the year with success.

Any help would be appreciated, thanks!

**Comment by orta** [comment]
Could the this a `bundle exec` vs global gems issue?
We've had `pod keys get` in there for a long time

**Comment by ruddfawcett** [comment]
Interesting... Yeah -- I've used `get` in the past with success.  On further investigation, I seem to have a different version of CocoaPods when accessing the gem via Terminal, than when I use it in a run script.  (Only got that far after resetting every gem on my system, and modifying paths).  Closing this because it's not a `cocoapods-keys` related issue, Xcode is using a different path.

**Comment by Isuru-Nanayakkara** [comment]
I'm trying to do exactly this. Extract the Fabric API key and secret into CocoaPods-Keys. The problem I'm facing is slightly different.

When I this in the Run Script, 
`"${PODS_ROOT}/Fabric/Fabric.framework/run" pod keys get FabricAPIKey`, I get the following build error.

![1](https://cloud.githubusercontent.com/assets/2551877/10903765/30c52ade-8233-11e5-8069-3892bd138574.png)

I tried outputting the key `FabricAPIKey` like this `pod keys get FabricAPIKey` and it works. However I'm seeing that same warning message that you got.

![2](https://cloud.githubusercontent.com/assets/2551877/10903784/5e87db2e-8233-11e5-8c8d-9667c4058e31.png)

Were you able to resolve this? If so please share how.

**Comment by segiddins** [comment]
You might need to put `pod keys get FabricAPIKey` in backticks. And the UTF-8 warning shouldn't actually break anything, but you could put `LANG=en_US.UTF-8 command_to_execute` to silence it.

**Comment by Isuru-Nanayakkara** [comment]
That was it! It's all working fine now. Thank you!

**Comment by fabioknoedtbcgdv** [comment]
hey @Isuru-Nanayakkara, how did you resolve that?

    "${PODS_ROOT}/Fabric/Fabric.framework/run" `pod keys get FabricAPIKey` ?
