### ISSUE TITLE
no implicit conversion of nil into String error when running pod keys command

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [orta/cocoapods-keys#117]
### Command

```
/usr/local/bin/pod keys
```
### Report
- What did you do?

I simply ran the `pod keys` command to view the keys I had added to a project beforehand.

**NOTE**: This didn't use to happen. The day before I had another project with two keys saved with cocoapods-keys. I removed them because I was deleting the project from my disk. After successfully removing the two keys, I just ran `pod keys` to see if it's all gone. Then this error occurred! I ignored it then. This error came back when I ran `pod keys` on a new project. It _does_ show the existing keys but this error template is also showing at the end. 
- What did you expect to happen?

Only show a list of existing keys.
- What happened instead?

Shows the list of keys but with the error as well.
### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.1 (15B42)
       Xcode : 7.1 (7B75)
         Git : git version 2.4.9 (Apple Git-60)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 58f41522a50887dfc00f3dd6e95bfc08fe11dc46
               RWPodSpecs - https://github.com/Isuru-Nanayakkara/RWPodSpecs.git @ 3c5426ba67e168fb3f361e87ab1c1af4506bf20b
```
### Plugins

```
cocoapods-deintegrate : 0.2.1
cocoapods-keys        : 1.5.2
cocoapods-plugins     : 0.4.2
cocoapods-search      : 0.1.0
cocoapods-stats       : 0.6.2
cocoapods-trunk       : 0.6.4
cocoapods-try         : 0.5.1
```
### Podfile

``` ruby
platform :osx, '10.9'
use_frameworks!

pod 'LetsMove'
```
### Error

```
TypeError - no implicit conversion of nil into String
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.5.2/lib/pod/command/keys/list.rb:44:in `+'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.5.2/lib/pod/command/keys/list.rb:44:in `display_keyring'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.5.2/lib/pod/command/keys/list.rb:25:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.5.2/lib/pod/command/keys/list.rb:24:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.5.2/lib/pod/command/keys/list.rb:24:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by aashcherbakov** [comment]
I have the same issue. @Isuru-Nanayakkara were you able to resolve it?

**Comment by mcdave029** [comment]
Having this issue too. any fix? @Isuru-Nanayakkara @aashcherbakov thanks in advance

**Comment by mcdave029** [comment]
Mine is now working its just that i have another project with unset keys. seems that `pod keys` command finding all keys

**Comment by ykws** [comment]
@mcdave029 Hello, when you did to unset keys, `pod keys rm` ?

**Comment by ykws** [comment]
Resolve if reset `pod keys set` to all deleted projects,
but reappear if unset all keys in one's project `pod keys rm` .
