### ISSUE TITLE
No such module Keys

### ISSUE THREAD

**Issue by BalestraPatrick** [orta/cocoapods-keys#119]
Hey! I'm trying to use two of my keys in my Swift project by following the instructions [here](https://github.com/orta/cocoapods-keys/blob/master/SWIFT_PROJECTS.md).

By doing `pod keys` I can see my keys correctly stored but it looks like that the `Keys` module is not built because when I try to import it's not found. 
![screen shot 2015-11-07 at 1 21 49 pm](https://cloud.githubusercontent.com/assets/3658887/11015140/881b6556-8552-11e5-9059-59e91e61a251.png)
I couldn't find any related issues.

**Comment by marcelofabri** [comment]
Could you post your `Podfile` here?

**Comment by BalestraPatrick** [comment]
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!

pod 'RxAlamofire', '~> 0.3'
pod 'Fabric'
pod 'Crashlytics'
pod 'Answers'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'Alamofire', '~> 3.0'
pod 'RxSwift', '~> 2.0.0-beta'

plugin 'cocoapods-keys', {
  :project => "TweetsCounter",
  :keys => [
    "FABRIC_API_KEY",
    "FABRIC_BUILD_SECRET",
  ]}

**Comment by BalestraPatrick** [comment]
Doing a `pod install` once again fixed the issue.

**Comment by sonvirgo** [comment]
```platform :ios, '10.0'

target 'TunnelsMux' do
    pod 'OpenSSL-Universal', '1.0.2.17'
    pod 'PsiphonTunnel', :git => 'https://github.com/Psiphon-Labs/psiphon-tunnel-core-iOS-library.git'
    pod 'OCSPCache', :git => "https://github.com/Psiphon-Labs/OCSPCache.git", :commit => '71e9f5d'
    #pod 'OCSPCache', :path => "../../../../../OCSPCache/"
    plugin 'cocoapods-keys', {
      :project => "TunnelsMux",
      :keys => [
        "myKey",
        "myIv",
        ]
    }
end
```
pod install
all key set ok
pod created ok

no such module Keys
Swift```import Key```
