### ISSUE TITLE
Continuous Integration - How to do it

### ISSUE THREAD

**Issue by unclesamer** [orta/cocoapods-keys#121]
Hello,
I am trying to implement continuous integration for one iOS project, and I am in the process of researching the best tool (Travis, Bitrise...) The problem I keep facing is that my project uses cocoapod-keys and I don't commit the keys files to git to keep them safe.

I kept on searching for a solution, and I only found that I should be using environment variables based on this post: http://artsy.github.io/blog/2015/01/21/cocoapods-keys-and-CI/

However, I am not really able to do so because even if I use an environment variable for a key, the build will fail since the keys.h/.m files do not exist.

So I am wondering if someone can post an example on how to use cocoapods-keys in an CI environment. Also it would be useful to have an integration in travis/bitrise.

Many thanks

**Comment by ashfurrow** [comment]
Hey there! We solve this by setting the keys in Travis' install step, then running `pod install`, which will generate the .h/.m files. We actually use [fake keys](https://github.com/artsy/eigen/blob/455954146ad4939a98ba7b856a0840e7d1ad6a82/Makefile#L40) but you could use secure environment variables to store real ones. 

Does that answer your question?

**Comment by ashfurrow** [comment]
(Well, mostly fake keys.)

**Comment by unclesamer** [comment]
Hello,

Yes, I guess you answered me. I will try setting fake keys then running `pod install` 

Thank you!
