### ISSUE TITLE
should I add the keys' file to .gitignore?

### ISSUE THREAD

**Issue by funkyLover** [orta/cocoapods-keys#122]
after set key's value,
and check the project's status by using `git status`
it will always change `cocoaPodsKeys/xxxKeys.h(m)`
but I commit that change and my teammate update the project local
it seem make nothing different..
can I add the keys' file to .gitignore? or should I ??

**Comment by ashfurrow** [comment]
Yes, the keys should never be checked in. We don't check in our Pods directory, but you can ignore the specific .h/.m files too.

**Comment by funkyLover** [comment]
thanks~
