### ISSUE TITLE
A pod key's value is returned wrong

### ISSUE THREAD

**Issue by sasikiran** [orta/cocoapods-keys#152]
I have a strange issue. I think this worked correctly in v1.6.0 when I shipped an app with cocoapod-keys.

I have a key configured with value: bt@tE$@tE@#@$#
However, when I print the key, it is showing this: bt@tEtE@#@0

I tried removing and re-adding the key number of times. It still returns me the wrong value.

Is there a workaround?

**Comment by orta** [comment]
This is really odd, can you verify it is what you think it is in the Keychain? ( should be something like "CocoaPods-Keys-project-keyname"

**Comment by sasikiran** [comment]
Thanks Orta. The issue was that there were multiple entries in the keychain. Removing all keys and re-adding fixed the issue.
