### ISSUE TITLE
Nullability annotations for generated Objective C keys classes

### ISSUE THREAD

**Issue by Skogetroll** [orta/cocoapods-keys#154]
Is it possible to add [nullability annotations](https://developer.apple.com/swift/blog/?id=25) for generated classes?

It would mainly help `Swift` developers, because it would be easier to guess either `keys.someKey()` always returns value or can return `nil`.

**Comment by orta** [comment]
Sure, send a PR

**Comment by Skogetroll** [comment]
Done: https://github.com/orta/cocoapods-keys/pull/155

Also, is there any reason why keys are `methods` and not a properties?

For `Objective C` both are almost interchangable in calling syntax, but for `Swift` there's difference, small (methods have parenthesis and properties don't), but still. And all those generated key code looks more like readonly properties than methods.

So maybe change like this is preferrable?
```diff
- - (NSString *)<%= key %>;<% end %>
+ @property (readonly) NSString *<%= key %>;<% end %>
```

**Comment by orta** [comment]
I think this was because of some runtime hackery, can't remember anymore 👍 

Give it a shot, and if it works, I'm happy to have it as properties

**Comment by Skogetroll** [comment]
#157 : I guess, runtime hackery were prevented because of auto-generated getter, but with `@dynamic` everything works fine.
