### ISSUE TITLE
Key input versus output

### ISSUE THREAD

**Issue by bakeddean** [orta/cocoapods-keys#169]
Hi, I'm having some trouble inputting a key then retrieving it.
Our key has some '$' characters in it. I've tried:
```
$ pod keys set "apiKey" "[characters]\$[characters]"
```
and
```
$ pod keys set "apiKey" '[characters]$[characters]'
```
Where [characters] are various alpha-numeric characters.

When I type pod keys it looks like the right values have been set.

But in the iOS code, the String has backslashes at the start and end.
In the debug inspector it looks like
```
"\\[characters]$[characters]\\"
```
or printed out it looks like
```
\[characters]$[characters]\
```
Probably something obvious, but I can't figure this one out.
Thanks.

**Comment by bakeddean** [comment]
I think a problem with derived data. Resolved.

**Comment by orta** [comment]
Ah, my sympathies 👍
