### ISSUE TITLE
Can use one key with Multi-target?

### ISSUE THREAD

**Issue by vnntsu** [orta/cocoapods-keys#179]
Actually, I want to use one key but with each key has different value depending on target that that key belong to.
So How can I do that?
Thanks....

**Comment by ashfurrow** [comment]
I don’t think you’ll be able to do that with just CP-Keys. I would create a different key for each target and then access the different keys depending on the target. You can do that by defining macros with a different name on each target and checking at runtime which one is defined. Good luck!

**Comment by vnntsu** [comment]
@ashfurrow oh, I got it. Thanks!
