### ISSUE TITLE
Commit 7b95b95 breaks our watchOS builds

### ISSUE THREAD

**Issue by jcayzac** [orta/cocoapods-keys#180]
Hi Orta,
Any particular reason you’re now restricting Cocoapods Keys to the iOS platform only?
Thank you

**Comment by the-pear** [comment]
Build log:
> Resolving dependencies of `Podfile`
> [!] The platform of the target `Watch Extension` (watchOS 4.0) is not compatible with `Keys (1.0.1)`, which does not support `watchos`.

**Comment by jcayzac** [comment]
That commit also probably breaks tvos

**Comment by jcayzac** [comment]
(and macos)

**Comment by orta** [comment]
Sure, happy to have the other platforms added 👍

**Comment by jcayzac** [comment]
I was about to send a PR fixing this issue but @segiddins beat me to it. Except #181 actually doesn't fix anything and sets version numbers that have no root in reality. It will be another 5 years at least until anybody hears of WatchOS 8.3… 👎

**Comment by jcayzac** [comment]
I understand this plugin is "done" but it seems to me it currently means "unmaintained". That #181 was merged with no testing is bad. Have you considered transferring it to somebody else?

**Comment by segiddins** [comment]
>  It will be another 5 years at least until anybody hears of WatchOS 8.3… 👎

I forgot that watchOS didn't have the same version as iOS

**Comment by orta** [comment]
@jcayzac please be more respectful on these issues, it's great that you're contributing but I'd rather it not come with an attitude. You're welcome to help out and improve things you think are not working.
