### ISSUE TITLE
cache problem in Xcode 10.1 new build system

### ISSUE THREAD

**Issue by xiangyu-sun** [orta/cocoapods-keys#191]
I have two keys, somehow Xcode 10.1 cached them. if I don't cleanup the build folder, the the file will be updated by pod install, while Xcode will continue to use the cached version.

Is this case, every build should clean the derived data if we are planing changing the key?

**Comment by orta** [comment]
The file's content changes, so Xcode should pick it up - might just be a temporary bug in Xcode

**Comment by xiangyu-sun** [comment]
yea, currently we are just doing a force cleanup of the build folder every time
