### ISSUE TITLE
How to update stored keys value ?

### ISSUE THREAD

**Issue by TheAbstractDev** [orta/cocoapods-keys#200]

**Comment by ashfurrow** [comment]
You can update a single stored value either by modifying it in `Keychain Access.app` on you Mac, or by running `pod keys set KEY_NAME VALUE`.

**Comment by TheAbstractDev** [comment]
That was so obvious ... Thanks !

**Comment by ashfurrow** [comment]
No worries! You can see how to interact with it more broadly by running `pod keys --help`. Take care!
