### ISSUE TITLE
Not working with bitcode_enabled NO flag

### ISSUE THREAD

**Issue by muddsar** [orta/cocoapods-keys#201]
i am currently playing with Cocoapods-keys & observed that it doesn't work if bitcode_enabled is NO. values are embeded as plain text in Keys.Framework/Keys file. Can you please confirm if this is the expected behaviour?

**Comment by orta** [comment]
They should be accessible at runtime as plain keys, but I'd be surprised that they show up as raw values in the binaries though, the code in your app looks like this:

https://github.com/orta/cocoapods-keys/blob/master/templates/Keys.m.erb#L36-L48

And never writes the raw values anywhere

**Comment by muddsar** [comment]
Here is the steps i am taking.

1. - Go to XCode->Build Settings->Enable Bitcode, Set to NO
2. - Archive the app & export for AppStore
3. - Go to the exported folder, Unarchive the .ipa
4. - Go to Payload folder
5. - Select .app -> Right click->Show Package Contents->Frameworks->Keys.Frameworks->Keys
6. - Open the Keys using any editor.
7. - Search for the value of the Key. In my cases two values are "testClient", "testSecret"

![image](https://user-images.githubusercontent.com/303103/77584439-2b23e800-6eb9-11ea-8719-93a3f1daab30.png)

In screenshot attached you can see you can see the values in plain text. Altough last part has been chopped in sample project, In real project few of the keys are exposed without chopping. Let me know if you needs further information.
Thanks

**Comment by orta** [comment]
Interesting, yeah, apple must have improved their compiler since I built this 6 years back, maybe it is inlining the string accessors in C now. 

I'm open to an alternative templates which don't have this issue 👍 - that could be as simple as ussing the NSString API instead of a c array or other alternatives

**Comment by orta** [comment]
OK, that's updated and shipped as 2.2.0 - great find @muddsar

**Comment by muddsar** [comment]
Great, Thanks again for the awesome fix guys :)

**Comment by ashfurrow** [comment]
@muddsar thank you for including such clear steps to reproduce! It made testing the fix really straightforward 👍

**Comment by muddsar** [comment]
@ashfurrow you are welcome. Looks like your PR was merged in but release commit failed the pipeline :( i hope it will be resolved soon. 
Keep up the good work :)

**Comment by ashfurrow** [comment]
@muddsar It looks like it's published here? I've been able to `bundle update cocoapods-keys` successfully, and re-running `bundle exec pod install` got me the fixed version: https://rubygems.org/gems/cocoapods-keys/versions/2.2.0

**Comment by muddsar** [comment]
@ashfurrow Thanks for the correction, i was looking at the releases & tags in the repository. i tried the instructions you provided & it works like a charm.
