### ISSUE TITLE
Too many Xcode projects issue

### ISSUE THREAD

**Issue by vitasapple** [orta/cocoapods-keys#213]
I want to remove a key and I use command "pod keys rm kckey" , then terminal warn me :"CocoaPods-Keys found too many Xcode projects (TCBeautyPanel.xcodeproj TankCat.xcodeproj UGCKit.xcodeproj). Please give a name for this project."
I know kckey is in TankCat project , so I input TankCat .
finally ,terminal give me an error :"[!] Could not find a project to remove the key from."
How can I do  to delete the key?

**Comment by SlaunchaMan** [comment]
IIRC you need to include the file extension. Try `pod keys rm kckey TankCat.xcodeproj`.

**Comment by vitasapple** [comment]
Thank you , I try your command. First I go to my project "cd /Users/apple/Desktop/tankemao-ios" , then I execute the command "pod keys rm closeBag TankCat.xcodeproj" and I get an error "[!] Could not find a project to remove the key from."

**Comment by vitasapple** [comment]
> IIRC you need to include the file extension. Try `pod keys rm kckey TankCat.xcodeproj`.

I know, because I changed the name of the root directory of the project, which caused the command to fail, now I change it back, there is no problem
