### ISSUE TITLE
How can I remove a Keyring?

### ISSUE THREAD

**Issue by VanegasDev** [orta/cocoapods-keys#216]
I was working in a forked project and now I don't want the keyring for that project anymore. I executed ` pod keys rm --all` but the keyring is still there and I'm having conflicts. 😞 Could somebody help me?

**Comment by ashfurrow** [comment]
You can delete the keyring using `Keychain Access.app`, which is installed on your computer. You can also remove the `.yml` files from `~/.cocoapods/keys` directory (look in the file's `name` section to get the right one).

**Comment by VanegasDev** [comment]
I had already tried using the Keychain Access App but I was just able to manage just the keys.

Right now I tried what you said about the .yml file and that works perfectly! Thank you so much @ashfurrow
