### ISSUE TITLE
Support multiple projects

### ISSUE THREAD

**Issue by rogerluan** [orta/cocoapods-keys#222]
Hey 👋 

I was looking for a way to support multiple projects within the same Podfile (same xcworkspace), with different keys, and it doesn't seem to be possible to do that. I tried declaring `plugin 'cocoapods-keys', { … }` twice in my Podfile, but no luck. Apparently only one of them gets really used. 

Is there any way to do this? If not, could anyone give me some leads on how I could implement this feature myself? 
Highly appreciate all the help 🙏

**Comment by rogerluan** [comment]
By briefly checking the codebase, I realized that it probably won't be an easy task to add support to multiple projects 😬 I might be just better off using multiple workspaces/podfiles instead

**Comment by orta** [comment]
The codebase is only about 650 LOC and pretty well tested, it should be easy to make the kind of changes you're interested in

**Comment by rogerluan** [comment]
I decided to roll my own tool for this: https://github.com/rogerluan/arkana it covers this scenario but also other limitations that I believe many other people have 😇 

Thanks @orta for the inspiration and for creating this amazing tool! 🙌 

I'm gonna close this issue as I don't intend to work on it anymore 🙇
