### ISSUE TITLE
Your Podfile requires that the plugin `cocoapods-keys` be installed. Please install it and try installation again.

### ISSUE THREAD

**Issue by MhMudSalAh** [orta/cocoapods-keys#234]
I have this error in M1 MAX & Monterey 12.6.1 & Xcode 14.1 & Ruby 3.1.2

I couldn't solve this problem with all possible solutions 
and I did all steps in this [Article](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/)
and setup "gem install cocoapods-keys" and I have the same error, however I have ruby version 3.1.2
Can anyone solve this problem ?!!

**Comment by mattneub** [comment]
You've already said this in a comment on the same issue elsewhere: https://github.com/orta/cocoapods-keys/issues/232#issuecomment-1321002761 I doubt that it needs a separate issue.

**Comment by orta** [comment]
Agree

**Comment by MhMudSalAh** [comment]
@orta 
Hello, I hope you are fine 
you closed this issue and it was not resolved.
Thanks a lot
