### ISSUE TITLE
Generated Keys implementation contains warnings

### ISSUE THREAD

**Issue by neonichu** [orta/cocoapods-keys#29]
The static data char array is too long in my case (two keys, so really mild usage):

```
initializer-string for char array is too long
```

![screen shot 2015-01-30 at 13 54 23](https://cloud.githubusercontent.com/assets/118992/5975913/c7d3c3f8-a887-11e4-8674-78926f0aec1e.png)

**Comment by orta** [comment]
That's odd, any idea what amount of chars is "too many"?

**Comment by neonichu** [comment]
Ah, it's actually not about the absolute length, but simply that there's a mismatch between declared size and actual size of the string. In my case the array is declared with 2204 chars, but the string literal has 2207. I'll look at the calculation and send a PR.
