### ISSUE TITLE
Keys framework doesn't exist in Pods project after install

### ISSUE THREAD

**Issue by ricardopereira** [orta/cocoapods-keys#35]
I'm working with 0.36.0.beta.2 with CocoaPods Keys plugin (0.9.5).

I create a Podfile with:

    plugin 'cocoapods-keys', {
      :project => "Contribuinte",
      :keys => [
        "SecretKey",
        "Algorithm"
      ]
    }

I run `pod install` and the output was:

    Analyzing dependencies
    Downloading dependencies
    Generating Pods project
    Integrating client project

    [!] [Hooks] The use of hooks without specifying a `plugin_name` has been deprecated.

    [!] [!] The Podfile does not contain any dependencies.

Then I check the keys with `pod keys` and nothing appears.

I set each key manually:

    pod keys set "SecretKey" "xxxxxxxxxx"
    pod keys set "Algorithm" "xxxxxxxxxx"

Recheck the keys with `pod keys`:

    Keys for Contribuinte
     ├  SecretKey - xxxxxxxxxx
     └  Algorithm - xxxxxxxxxx

Tried again `pod install` and:

    Analyzing dependencies
    Downloading dependencies
    Generating Pods project
    Integrating client project

    [!] [Hooks] The use of hooks without specifying a `plugin_name` has been deprecated.

    [!] [!] The Podfile does not contain any dependencies.

No Keys framework!

BTW, it's a swift project.

**Comment by orta** [comment]
```
   cocoapods-keys   master ✔  gem push pkg/cocoapods-keys-1.0.0.gem
Pushing gem to https://rubygems.org...
Successfully registered gem: cocoapods-keys (1.0.0)
```

I've just his second pushed 1.0.0, which should fix this, can you try?

**Comment by ricardopereira** [comment]
Updating:

    Updating installed gems
    Updating cocoapods-keys
    Fetching: cocoapods-keys-1.0.0.gem (100%)
    Successfully installed cocoapods-keys-1.0.0
    Parsing documentation for cocoapods-keys-1.0.0
    Installing ri documentation for cocoapods-keys-1.0.0
    Installing darkfish documentation for cocoapods-keys-1.0.0
    Done installing documentation for cocoapods-keys after 1 seconds
    Gems updated: cocoapods-keys

Retry `pod install`:

    Analyzing dependencies
    Pre-downloading: `Keys` from `https://github.com/ashfurrow/empty-podspec.git`
    Downloading dependencies
    Installing Keys (1.0.1)
    Generating Pods project
    Integrating client project

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Contribuinte` to `Pods/Target Support Files/Pods/Pods.debug.xcconfig` or include the `Pods/Target Support Files/Pods/Pods.debug.xcconfig` in your build configuration.

:) Thank you

**Comment by orta** [comment]
rock
