### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by ashfurrow** [orta/cocoapods-keys#46]
We need some tests around our code, even just basic ones.

**Comment by lyricsboy** [comment]
I made a start at this [on my fork](https://github.com/lyricsboy/cocoapods-keys/tree/lyricsboy/unit-tests). Take a look and let me know what you think.

So far it does some nice things to extract the ERB into template files and makes the header date injectable/repeatable in test.

**Comment by ashfurrow** [comment]
Cool! Checking out the diff here: https://github.com/orta/cocoapods-keys/compare/master...lyricsboy:lyricsboy/unit-tests

**Comment by ashfurrow** [comment]
Looks great so far!

**Comment by lyricsboy** [comment]
Right on, I'll keep going then :)

**Comment by ashfurrow** [comment]
:tada:
