### ISSUE TITLE
Updating to 1.0.2 requires inputting name of project

### ISSUE THREAD

**Issue by nanoxd** [orta/cocoapods-keys#47]
Hi,

Using `1.0.1` I had no issue with running `pod install` or `pod update`. With `1.0.2`, I get a `Hello there, we found too many xcodeprojects. Please give a name for this project.` multiple times during the update/install.

![cocoapod-keys](https://cloud.githubusercontent.com/assets/1889575/6642522/6f72a390-c962-11e4-9492-b90a58d538cf.png)

Directory only contains one .xcodeproj as well as `Pods.xcodeproj`. Is this something on my end or is the search for projects going to deep and inadvertently picking up `Pods.xcodeproj`?

**Comment by orta** [comment]
That's possible, I don't think we reject the `Pods.xcodeproj`. Good call!

**Comment by ashfurrow** [comment]
Hmm, yeah that's likely. Do you specify the project name in the Podfile? 

```ruby
plugin 'cocoapods-keys', {
  :project => "Eidolon",
  :keys => [
    "ArtsyAPIClientSecret",
    "ArtsyAPIClientKey",
    "HockeyProductionSecret",
    "HockeyBetaSecret",
    "MixpanelProductionAPIClientKey",
    ...
  ]}
```

**Comment by nanoxd** [comment]
Yes, I switched the syntax from Ruby 1.8 to Ruby 1.9's as well. Podfile: 

```ruby
platform :ios, '8.0'
use_frameworks!

# Networking
pod 'AFJSONRPCClient', path: "~/Dev/OSS/AFJSONRPCClient"
pod 'Async', git: "https://github.com/duemunk/Async.git"
pod 'SwiftyJSON'
pod 'SwiftyUserDefaults'

# UI
pod 'BLKFlexibleHeightBar'
pod 'CNPPopupController'
pod 'JTCalendar', '~> 1.1'
pod 'MONPromptView'

plugin 'cocoapods-keys', {
  project: "Client",
  keys: [
    "ClientAPIKey",
    "ClientAPISecret",
  ]
}
```

**Comment by marcelofabri** [comment]
This even happened without adding the plugin to my Podfile.

**Comment by orta** [comment]
Same, fixing right now :+1:

**Comment by abbeycode** [comment]
I'm getting this now also, even with the project specified, as everyone is saying (in a directory with a single project, aside from the Pods project itself).

**Comment by abbeycode** [comment]
Sorry, any updates on this? @orta ?

**Comment by danthorpe** [comment]
Hmm, has anyone got any ideas on how to fix this? It's a blocking issue, especially as it can happen on a build machine.

**Comment by ashfurrow** [comment]
Looks like it was addressed in #58; we went with Podfile-specified project name _only_ to not ask questions.

**Comment by danthorpe** [comment]
Yeah, just to confirm, moved my build machine to bleeding edge of cocoapods-keys and this issue is resolved. :)

**Comment by ashfurrow** [comment]
:tada:

**Comment by ashfurrow** [comment]
Thanks for testing!

**Comment by abbeycode** [comment]
Thanks guys! Do you have a target date for when 1.0.3 may be released? Otherwise, @danthorpe what do I need to do to get the "bleeding edge" build?

**Comment by nanoxd** [comment]
@abbeycode 
```
gem 'cocoapods-keys', git: 'git@github.com:orta/cocoapods-keys.git'
```

**Comment by orta** [comment]
I don't think master is even 100% working yet, I've been struggling to get it solid so far, was in the code-base ATM, gonna try get something out today though.

You can use a specific gem version by using a [Gemfile](https://github.com/artsy/eigen/blob/master/Gemfile) and specifying a specific repo.

**Comment by danthorpe** [comment]
@abbeycode I wouldn't recommend using master - I was in a bind, and used the `specific_install` gem. 

```
gem install specific_install
gem specific_install https://github.com/orta/cocoapods-keys
```

Also, I see that #55 also seems to be resolved on master.

**Comment by orta** [comment]
OK, looks like I'm happy, all of the use cases seem to be working for me. Will push a `1.1.0`.

**Comment by danthorpe** [comment]
Yay! :+1:

**Comment by orta** [comment]
deployed
