### ISSUE TITLE
Best way for CI to read keys

### ISSUE THREAD

**Issue by esttorhe** [orta/cocoapods-keys#52]
Right now whenever I try to launch a build it will fail because its going to reach the point where the plugin asks for the keys to be entered for "the first time".

I saw that on `Eidolon` you guys embed the keys on the `Makefile` and on the `CI` server I assume you run that task first to add the keys to the keyring then just perform `pod install` as usual.

But to me it kinds of defeats the purpose of the plugin because I would be storing my keys on an unencrypted file on my repo which doesn't sound so secure after all.

Is there a better way of doing this? Am I doing something wrong regarding `CI` and `cocoapods-keys` here?

<p align="center"><img src="http://i.giphy.com/LK4rMvkSAJcdi.gif"/></p>

**Comment by ashfurrow** [comment]
Our keys in Eidolon are mostly blank (just `-`). You can use [Travis' secure environment variables](http://docs.travis-ci.com/user/environment-variables/#Secure-Variables) instead for real API keys. We do this for our [GitHub API Key](https://github.com/artsy/eidolon/blob/ac2f12eeb1b30326d538bef92f22da7b25651a62/.travis.yml#L8) to access private pods.

**Comment by esttorhe** [comment]
Mmm; I'm currently not using Travis but [`BITRISE`](https://www.bitrise.io); will have to check if there's something similar.

Thanks for the quick answer though :bow:

**Comment by ashfurrow** [comment]
No problem! Let me know what you think of them – currently considering moving off of Travis.

**Comment by DarthMike** [comment]
@esttorhe Did you find a way to integrate with Bitrise? I'm having similar issue.

**Comment by pavm035** [comment]
Any idea how to make it work on Jenkins ?

**Comment by orta** [comment]
Environment variables will work in Jenkins and Bitwise too

**Comment by pavm035** [comment]
Thanks @orta !, I have another question looking at this issue will be a problem when we use this in CI.
https://github.com/orta/cocoapods-keys/issues/113
