### ISSUE TITLE
No OS X compatibility?

### ISSUE THREAD

**Issue by abbeycode** [orta/cocoapods-keys#53]
When I try to run a `pod install`, with the podfile below, I get the following error (after providing the project name 4 times, as described in Issue #47):

> [!] The platform of the target `Pods` (OS X 10.9) is not compatible with `Keys (1.0.2)` which has a minimum requirement of iOS 7.0.

    source 'https://github.com/CocoaPods/Specs.git'
    platform :osx, '10.9'

    ...

    plugin 'cocoapods-keys', {
        project: "ProjectName",
        keys: [
            "APIKeyName"
        ]
    }

Is this a bug, or is there no support for OS X projects?

**Comment by orta** [comment]
This is a bug for sure.

**Comment by abbeycode** [comment]
Fix confirmed, thanks
