### ISSUE TITLE
"CocoaPods did not set the base configuration of your project..."

### ISSUE THREAD

**Issue by abbeycode** [orta/cocoapods-keys#54]
I have been using CocoaPods for a while with my project, which has four targets. Now that I installed cocoapods-keys, I get the following message each time I run `pod install`, even with the same `podfile` as before, that doesn't include the Keys plugin:

> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `TargetName` to `Pods/Target Support Files/Pods/Pods.debug.xcconfig` or include the `Pods/Target Support Files/Pods/Pods.debug.xcconfig` in your build configuration.
>
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `TargetName` to `Pods/Target Support Files/Pods/Pods.release.xcconfig` or include the `Pods/Target Support Files/Pods/Pods.release.xcconfig` in your build configuration.

All four of the project's targets point to `Pods-TargetName.<debug/release>.xcconfig`, so I'm not sure why it's popping up only for one of the four targets. The only way to stop the message is to uninstall cocoapods-keys.

**Comment by abbeycode** [comment]
I'm still seeing this in v1.2.1. Any ideas?

**Comment by nubbel** [comment]
@abbeycode explicitly setting the target name solved it for me. Try that:

```
plugin 'cocoapods-keys', {
    :project => "ProjectName",
    :target => "TargetName",
    :keys => [
        "APIKey"
    ]
}
```

**Comment by abbeycode** [comment]
Thanks @nubbel, that did it!

**Comment by serluca** [comment]
same here, not sure is a good idea to close this issue

**Comment by abbeycode** [comment]
@serluca Were you able to fix it by specifying the target name? That worked for me, which is why I closed it.

**Comment by serluca** [comment]
@abbeycode yes it works specifying the target, thanks
