### ISSUE TITLE
Application code example in Swift

### ISSUE THREAD

**Issue by moubry** [orta/cocoapods-keys#65]
It'd be amazing if the README had an example for integrating `cocoapods-keys` into a Swift project.

For reference, I was able to get it working using information from:

* https://github.com/orta/cocoapods-keys/issues/36
* https://medium.com/@stigi/swift-cocoapods-da09d8ba6dd2
* http://stackoverflow.com/a/27547731/369669

Thank you so much for maintaining such a valuable project!

**Comment by orta** [comment]
if someone wants to do this, I would recommend making a unique markdown file that can go into full details that we can link to in the README.

**Comment by orta** [comment]
This is in #79
