### ISSUE TITLE
Remove segiddins from the gemspec

### ISSUE THREAD

**Issue by segiddins** [orta/cocoapods-keys#70]
He hasn't contributed in ages, and probably none of his code is left.
He also sometimes talks in the third person.

**Comment by ashfurrow** [comment]
Mmm I'm on the side of _not_ removing him, since his help was instrumental in creating this tool and deserves "author" status. However, I would respect any decision he made.

**Comment by orta** [comment]
Nah, your foundational work was too important. Unless you very strongly want it removed, I'm keeping you on there.
