### ISSUE TITLE
Keys for multiple targets

### ISSUE THREAD

**Issue by abbeycode** [orta/cocoapods-keys#72]
I use API keys in files that are parts of different targets in my app. It's not totally clear how to do this, so I tried having the following in my Podfile:

```
plugin 'cocoapods-keys', {
    :project => "Comickaze",
    :target => "AppTarget",
    :keys => [
        "CrashlyticsAPIKey",
        "PaddleAPIKey"
    ]
}

plugin 'cocoapods-keys', {
    :project => "Comickaze",
    :target => "XPCServiceTarget",
    :keys => [
        "AmazonS3SecretKey",
        "FogBugzToken"
    ]
}
```

This way, the last one wins, and my `AppTarget` doesn't get linked against the generated Keys project. Any ideas?

**Comment by abbeycode** [comment]
I tried placing each `plugin` block inside of the `target do` block for their respective targets, with and without the `:target` specified, and that didn't make a difference.

**Comment by orta** [comment]
We ( Artsy) don't have any projects that use multiple targets, so I'm afraid right now that is totally untested, probably wouldn't be too hard to support though - the codebase is pretty small.

**Comment by abbeycode** [comment]
Why do you think the second call to the plugin removes what was done by the first call?

**Comment by segiddins** [comment]
You can only have one `plugin` call per plugin in your podfile.

**Comment by abbeycode** [comment]
@segiddins Ah, thanks, so then would the proper fix be to allow the `target` property to specify a list of targets?

**Comment by abbeycode** [comment]
Also, if I wanted to take a look at fixing this, what's the easiest way to switch to using a local clone? I'm not familiar enough with Ruby or Gems to configure that.

**Comment by orta** [comment]
You want to use a [Gemfile](https://guides.cocoapods.org/using/a-gemfile.html) - you can then use `gem "cocoapods-keys", :path => '/path/to/local-clone'`to specify a local gem. Here's an [example](https://github.com/artsy/eigen/blob/master/Gemfile) ( without the path ). 

You can only give a plugin a hash/dictionary, so it might make sense to do something like:

```
plugin 'cocoapods-keys', {
    :targets => {
        :project => "Comickaze",
        :target => "AppTarget",
        :keys => [
            "CrashlyticsAPIKey",
            "PaddleAPIKey"
      },
      {
        :project => "Comickaze",
        :target => "XPCServiceTarget",
        :keys => [
            "AmazonS3SecretKey",
            "FogBugzToken"
     }]
}
```

**Comment by abbeycode** [comment]
I've gotten something working now, using a list of target names. I'll submit a pull request once I'm comfortable with it.

The solution requires all targets to share a list of keys, which should be fine, and allowed for a simple implementation. Thanks for the help getting up and running.

The Podfile plugin call looks like this:

```
plugin 'cocoapods-keys', {
    :project => "Comickaze",
    :target => ["AppTarget", "XPCServiceTarget"],
    :keys => [
        "AmazonS3SecretKey",
        "CrashlyticsAPIKey",
        "FogBugzToken",
        "PaddleAPIKey"
    ]
}
```

**Comment by orta** [comment]
Yeah, do it! ( If you can make `target` work for both strings/arrays ( and ideally `target`/`targets`) that'd be amaze. )

**Comment by abbeycode** [comment]
I have it working for strings and arrays inside `target` - if I add `targets`, how strict should it be about enforcing strings in `target` and an array in `targets`?

**Comment by orta** [comment]
It shouldn't

**Comment by abbeycode** [comment]
I submitted a pull request. Not sure why it's not linking here: https://github.com/orta/cocoapods-keys/pull/77

**Comment by abbeycode** [comment]
I updated the pull request to pass the build

**Comment by abbeycode** [comment]
I added specs for the new code

**Comment by orta** [comment]
Fixed :+1:

**Comment by loudmouth** [comment]
This does not work for nested test targets as described in the [Cocoapod's Podfile documentation](https://guides.cocoapods.org/syntax/podfile.html).

Output of `pod install` is as follows:
```
Could not find a target named 'TEST_TARGET_NAME' in your Podfile. Stopping keys

```

**Comment by orta** [comment]
You're welcome to take a look at fixing this 👍

**Comment by loudmouth** [comment]
Sounds good @orta. I will start tackling this tomorrow. Would you prefer that I open a new issue? Or continue by link relevant comments/code here?

**Comment by orta** [comment]
New please :)

**Comment by cuddle-sujeet** [comment]
Hi, Thanks for this awesome Pod. I am facing the same issue that @loudmouth  faced.

Could not find a target named 'TEST_TARGET_NAME' in your Podfile. Stopping keys

Can you help me with this?
Thanks
