### ISSUE TITLE
Different keys for the same project

### ISSUE THREAD

**Issue by patoroco** [orta/cocoapods-keys#84]
I just used this plugin few minutes ago (I'm reviewing eidolon project, and it's needed), and I'm thinking to use in one of my apps where currently I've an ```APICredentials.h``` file with different configurations, i.e. PRODUCTION_KEYS, DEVELOPMENT_KEYS or STAGING_KEYS (each one of these configurations has different APIKey or APISecret and other values depending environment).

I'm thinking to create a script to 'load' keys inside this plugin, but I'm not sure if should be good to integrate directly in plugin and allow it to load different keys. I'm not the best in Ruby, but I could do a first approach for that :8ball: 

What do you think about that? Do you know a better option to do that? As I told before, this is my first meet with 'cocoapods-keys', so maybe I'm reinventing the wheel :)

**Comment by orta** [comment]
I think this could work, but I think its overkill for not much gain. You would end up with a DSL like:

``` ruby

  :keys => [
    "ArtsyAPIClientSecret",
    "ArtsyAPIClientKey",
    ...
  ]},
:production_keys => [
    "HockeySecret",
    "MixpanelAPIClientKey",
    ...
  ]},
:staging_keys => [
    "HockeySecret",
    "MixpanelAPIClientKey",
    ...
  ]}
```

Where it would generate 2 classes a `ThingProductionKeys` and a `ThingStagingKeys` which have different `HockeySecret` and `MixpanelAPIClientKey`, with different keys. But I don't feel like you're gaining much when you have the simplicity of a flat file vs al the hierarchy, personally. So unless you can write it and make sure it's well tested it might not be worth doing.

**Comment by orta** [comment]
My feels are that we're better off with simplicity in this respect, as you can just use uniquely named keys.
