### ISSUE TITLE
Missing Keys when we copy or move source code

### ISSUE THREAD

**Issue by anishroff** [orta/cocoapods-keys#90]
Hello,

Its awesome component and thanks for this. I faced 1 issue recently, e.g. I am using this in 1 project and for some reason I have to move the source code to different location. 

Now that Keys  in Development Pods under "Pods" project goes missing and that is due to fixed path I guess, I can see those files are there though. I have to again do "pod update" in order to get those files. 

Is it intentional ? or is it just as it is. 

Thanks,
Ani

**Comment by orta** [comment]
The last update should fix this! It will use project relative paths instead of absolute :+1:
