### ISSUE TITLE
Unknown command: `generate`

### ISSUE THREAD

**Issue by patoroco** [orta/cocoapods-keys#91]
Reading documentation I read about a `generate` command, I suppose that this should be useful to reload keys in .m file (in my case, I'm using several keys and I need to do `pod install` after change it).

The problem is that this command doesn't exist, and when I search in project, I saw that this command is not included (https://github.com/orta/cocoapods-keys/blob/master/lib/pod/command/keys.rb#L4-L7).

Do you remove this line intentionally? Or can I do my first contribution here? ;)

**Comment by orta** [comment]
yeah, sure add it in, and add it to the changelog :+1:

**Comment by robbiehanson** [comment]
The `generate` command was added via pull request #136.

**Comment by patoroco** [comment]
Oh, sorry @orta, but I didn't see your comment. It's nice than somebody added it meanwhile! :D
