### ISSUE TITLE
Remove path auto-expand in Podfile.lock to allow to share cocoapods-keys between team members

### ISSUE THREAD

**Issue by patoroco** [orta/cocoapods-keys#92]
I'm trying to use cocoapods-keys plugin in our app, but I saw that in Podfile.lock is generated an expanded path like `/myuser/mypaths/project/Pods/CocoaPodsKeys/`.

I was looking in eidolon project, and there they use a relative path (https://github.com/artsy/eidolon/blob/master/Podfile.lock#L112), so I changed the two lines manually.

The problem is that every time that I do a `pod install`, both lines are overridden like you can see in this git diff:
![screen shot 2015-06-25 at 14 15 29](https://cloud.githubusercontent.com/assets/701909/8354053/23d3aa3a-1b45-11e5-89d9-f7ea1415ad16.png)

Any suggestion about that?

**Comment by ashfurrow** [comment]
Interesting! Hmm. I've not seen that but we can investigate. Can you tell us which versions of CocoaPods and CocoaPods Keys you are using?

**Comment by patoroco** [comment]
Yep! I'm using Cocoa Pods 0.37.2 and CocoaPods Keys (1.3.1) (last versions)

**Comment by orta** [comment]
Looks like [here](https://github.com/orta/cocoapods-keys/blob/master/lib/plugin.rb#L54) - I wonder if here we can just use the relative path instead.

**Comment by patoroco** [comment]
Both of you haven't problem working in the same project (eidolon) with this Podfile.podlock?

**Comment by orta** [comment]
Looks like I'm still on 1.2.1 on my own project, Eidolon is [1.2.0](https://github.com/artsy/eidolon/blob/master/Gemfile.lock#L49)

**Comment by patoroco** [comment]
Ey, thanks @segiddins :)
