### ISSUE TITLE
Target visible

### ISSUE THREAD

**Issue by ashfurrow** [orta/cocoapods-keys#98]
The Keys target is visible in Xcode:

![screen shot 2015-07-02 at 3 43 49 pm](https://cloud.githubusercontent.com/assets/498212/8486235/5d73f42a-20d1-11e5-96e2-5f0e8ad3e9ae.png)

Additionally, the target becomes selected when doing a `pod install` or checking out a different branch.

**Comment by ashfurrow** [comment]
Opened an issue on CocoaPods. If they choose not to resolve the issue there, we can always use a `post_install` hook to do it ourselves.

**Comment by orta** [comment]
fixed in `1.5.0`

**Comment by ashfurrow** [comment]
:tada:
