### ISSUE TITLE
Keys is referencing two different projects for one single project

### ISSUE THREAD

**Issue by MaxKramer** [orta/cocoapods-keys#99]
Hi @orta great work, I really appreciate all you do for Cocoapods, it's certainly made my life a hell of a lot easier.

This is somewhat related to the #91, in that I'd like to use the `generate` command to try and fix the issue I'm having.

`Podfile`

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '7.0'

    inhibit_all_warnings!

    target 'Forecastr' do
        pod 'GoogleMaps'
        pod 'FlickrKit'
        pod 'PINCache'
        pod 'SDWebImage'
        pod 'RTFDiskCache'
    end

    target 'ForecastrTests', :exclusive => true do
        pod 'KIF'
    end

    plugin 'cocoapods-keys', {
        :project => "Forecastr",
        :keys => [
            "GoogleAPIKey",
            "FlickrAPIKey",
            "FlickrAPISecret",
            "DarkSkyAPIKey"
        ]
    }

`pod keys`

<img width="437" alt="screen shot 2015-07-10 at 01 49 22" src="https://cloud.githubusercontent.com/assets/542953/8610114/e6f4ec5c-26a5-11e5-9325-477ba986a817.png">

For a reason that I haven't yet been able to debug, Keys has generated two different references to the same project, "Forecastr", instead of having all keys under one reference.

The references found under `Forecastr - /Users/Max/code/github/forecastr/iOS` are directly accessible in the Xcode project, whereas those found under `Forecastr` on its own are not. When I add a new key i.e. `pod keys set DarkSkyAPIKey aaa`, the new key is added under the `Forecastr` reference and not under the `Forecastr - /Users/Max/code/github/forecastr/iOS` meaning that the keys are not accessible in the project.

Initially I tried debugging by reinstalling cocoapod-keys, upgrading cocoapods (already on the latest version) and then running `pod install` in order to trigger the `generate` command. This worked, however once again it generated the keys found under `Forecastr - /Users/Max/code/github/forecastr/iOS` instead of a conglomerate of both.

I appreciate that this is somewhat confusing, but I'd appreciate your help debugging.

Cheers!

Max.

**Comment by orta** [comment]
Can you try it with these settings please?

```
plugin 'cocoapods-keys', {
    :project => "Forecastr",
    :target => "Forecastr"
    :keys => [
        "GoogleAPIKey",
        "FlickrAPIKey",
        "FlickrAPISecret",
        "DarkSkyAPIKey"
    ]
}

```

**Comment by MaxKramer** [comment]
@orta that didn't work, but I tried changing the project name to "Forecaster" to see if it would create another set of keys. This in fact did work and reported some key mismatches, which, after entering the correct api keys etc... worked perfectly and the ForecastrKeys class was regenerated.
